[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'npm install --verbose'
]

[phases.build]
cmds = [
  'npm run build --verbose',
  'ls -la dist || dir dist'
]

[start]
cmd = 'node server.js'

[variables]
NODE_ENV = 'production'
